"""initial models

Revision ID: 969992514e32
Revises: 
Create Date: 2026-03-09 16:35:50.844612
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '969992514e32'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tutor_id', sa.Uuid(), nullable=False),
    sa.Column('join_code', sa.String(length=6), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'ACTIVE', 'COMPLETED', name='sessionstatus', native_enum=False), nullable=False),
    sa.Column('session_type', sa.Enum('LIVE', 'PRE_RECORDED', name='sessiontype', native_enum=False), nullable=False),
    sa.Column('student_display_name', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('session_type_label', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('join_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_join_code'), 'sessions', ['join_code'], unique=True)
    op.create_table('metric_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metric_snapshots_session_ts', 'metric_snapshots', ['session_id', 'timestamp_ms'], unique=False)
    op.create_table('nudges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('nudge_type', sa.Enum('STUDENT_SILENT', 'STUDENT_LOW_EYE_CONTACT', 'TUTOR_DOMINANT', 'STUDENT_ENERGY_DROP', 'INTERRUPTION_SPIKE', 'TUTOR_LOW_EYE_CONTACT', name='nudgetype', native_enum=False), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='nudgepriority', native_enum=False), nullable=False),
    sa.Column('trigger_metrics', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('tutor_metrics', sa.JSON(), nullable=False),
    sa.Column('student_metrics', sa.JSON(), nullable=False),
    sa.Column('talk_time_ratio', sa.JSON(), nullable=False),
    sa.Column('total_interruptions', sa.Integer(), nullable=False),
    sa.Column('interruption_attribution', sa.JSON(), nullable=False),
    sa.Column('flagged_moments', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('overall_engagement_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_summaries')
    op.drop_table('nudges')
    op.drop_index('ix_metric_snapshots_session_ts', table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_index(op.f('ix_sessions_join_code'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('tutors')
    # ### end Alembic commands ###
